# Copyright (c) 2022-2023 Pablo González Carrizo (unmonoqueteclea)
# Copyright (c) 2025-2026 Voogle Contributors
# All rights reserved.

FROM node:19-slim

WORKDIR /frontend

# we need curl for the health check
RUN apt-get update &&\
    apt-get install --no-install-recommends -y curl &&\
    rm -rf /var/lib/apt/lists/*

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm install

COPY ./ .

EXPOSE 5173

CMD ["npm", "run", "dev"]
