name: voogle

services:
  backend:
    image: ghcr.io/jbraseth/voogle-backend:latest
    ports:
      - ${VOOGLE_API_PORT:-81}:80
    command: uvicorn src.voogle.main:app --host 0.0.0.0 --port 80
    volumes:
      - ./data/:/data/
    healthcheck:
      test: ["CMD", "curl", "-f", "0.0.0.0/app/version"]
      interval: 6s
      timeout: 10s
      retries: 50

  frontend:
    image: ghcr.io/jbraseth/voogle-ui:latest
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - ${VOOGLE_FRONTEND_PORT:-80}:80
    healthcheck:
      test: ["CMD", "curl", "-f", "0.0.0.0:80"]
      interval: 6s
      timeout: 10s
      retries: 50

  management:
    image: ghcr.io/jbraseth/voogle-backend:latest
    ports:
      - ${VOOGLE_MANAGEMENT_PORT:-8501}:8501
    entrypoint: ""
    command: streamlit run src/voogle/management/🏠-Home.py
    volumes:
      - ./data/:/data/

  redis:
    image: redis:7.0.4-alpine
    hostname: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  worker:
    image: ghcr.io/jbraseth/voogle-backend:latest
    depends_on:
      redis:
        condition: service_healthy
    entrypoint: ""
    command: python src/voogle/worker.py
    volumes:
      - ./data/:/data/

  qdrant:
    image: qdrant/qdrant:v1.12.5
    expose:
      - 6333
    volumes:
      - ./data/qdrant/:/qdrant/storage
