# Copyright (c) 2025-2026 Voogle Contributors
# All rights reserved.

# pyright: reportUndefinedVariable=false, reportGeneralTypeIssues=false

"""add resources table

Revision ID: a1b2c3d4e5f6
Revises: 6baff69d05b2
Create Date: 2025-12-31 00:00:00.000000

"""
import ormar
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "6baff69d05b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resources",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("id", ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),  # type: ignore[attr-defined]
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("channel", sa.Integer(), nullable=True),
        sa.Column("episode", sa.Integer(), nullable=True),
        sa.Column("guid", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=False, server_default=""),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("local_path", sa.Text(), nullable=False, server_default=""),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("mime_type", sa.String(length=100), nullable=False, server_default="application/pdf"),
        sa.Column("extracted", sa.Boolean(), nullable=True, server_default="0"),
        sa.Column("embeddings", sa.Boolean(), nullable=True, server_default="0"),
        sa.ForeignKeyConstraint(
            ["channel"],
            ["channels.pk"],
            name="fk_resources_channels_pk_channel",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["episode"],
            ["episodes.pk"],
            name="fk_resources_episodes_pk_episode",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("guid", name="uc_resources_guid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resources")
    # ### end Alembic commands ###
